#!/bin/sh

# this was created based on my system, so change the path where the
# feh.bg will be located in yours in case you use this script

# removing any image files in my script folder

# !!! be careful if you change the directory where you use this !!!
# !!! check the code and read the prompt before doing something !!!

if [ -f $HOME/.scripts/*.png ]; then
    rm -i $HOME/.scripts/*.png

elif [ -f $HOME/.scripts/*.jpg ]; then
    rm -i $HOME/.scripts/*.jpg

else
    rm -i $HOME/.scripts/*.jpeg
fi

# copying and pasting wallpaper and then executing feh
cp $1 $HOME/.scripts

if [ -f $HOME/.scripts/*.png ]; then
    feh --bg-fill *.png

elif [ -f $HOME/.scripts/*.jpg ]; then
    feh --bg-fill *.jpg

else [ -f $HOME/.scripts/*.jpeg ]
    feh --bg-fill *.jpeg
fi

# better name
mv $HOME/.fehbg $HOME/.scripts/fehbg
