#!/bin/dash

selected=$(ps -a -u $USER | \
#           sort -r | \
           awk 'OFS=" " {print $1,$4}' | \
           sed '1d' | \
           dmenu -sb '#f7768e' -p "Kill process:")

if [ ! -z "$selected" ]; then

    answer=$(printf "Yes\nNo" | \
        dmenu -sb '#f7768e' -p "'$selected' will be killed, are you sure?")

    if [ $answer = "Yes" ]; then
        selpid=$(printf "$selected" | awk '{print $1}')
        kill -9 "$selpid" && notify-send "$selected" "was killed"
    fi
fi

exit 0
