#!/bin/dash
if [ $# = 1 ]; then
    case $1 in
        "inc") xbacklight -inc 1;;
        "dec") xbacklight -dec 1;;
        *) echo "Invalid option";;
    esac
fi
notify-send -t 1500 -h string:x-canonical-private-synchronous:luz "Brightness: $(xbacklight -get)" # this -h is working for now
