#!/bin/bash

# Touchpad
xinput --set-prop 'pointer:''Synaptics TM3096-006' 'libinput Tapping Enabled' 1
xinput --set-prop 'pointer:''Synaptics TM3096-006' 'libinput Accel Speed' -0.1

# Mouse
xinput --set-prop 'pointer:''SIGMACHIP Usb Mouse' 'libinput Accel Speed' -0.1
xinput --set-prop 'pointer:''SIGMACHIP Usb Mouse' 'libinput Accel Profile Enabled' 1, 0
