#!/bin/sh

# Não inicie
# simple script to stop $HOME/.config/autostart files to autostart
# this was made to stop those annoying programs

for file in $*
do
    echo "" > $file
    chmod 0400 $file
done

#echo "pinto" > $*
#chmod 0400 $*
