#!/bin/dash

# System management menu using dmenu
# Made by gabrielzschmitz
# https://github.com/gabrielzschmitz		  


# tried to use waffle for the icons
# but dmenu doesnt support multiple
# fonts
#
# in case you want the icons:
#
# it's working now
shutdown="  Shutdown"
reboot="  Restart "
logout="  Logout  "
suspend="  Sleep   "
lock="  Lock    "

# Options
#shutdown="⏻  Shutdown"
#reboot="  Restart "
#logout="  Logout  "
#suspend="⏾  Sleep   "
#lock="  Lock    "

# Variables
options="$shutdown\n$reboot\n$logout\n$suspend\n$lock"

# Choices
chosen="$(printf "$options" | dmenu -l 5)"
case $chosen in
    "$shutdown")
		notify-send "⏻ Turning off the machine..." &
                sleep 1  && systemctl poweroff
        ;;
    "$reboot")
		notify-send " Restarting the machine..." &
                sleep 1  && systemctl reboot
	;;
    "$logout")
		notify-send " Login out of the system..." &
                sleep 1  && loginctl terminate-session $XDG_SESSION_ID
	;;
    "$suspend")
		notify-send "⏾ Putting the system to sleep..." &
                sleep 1  && systemctl suspend
        ;;
    "$lock")
		notify-send " Locking the system..." &
                sleep 5.1 && betterlockscreen -l blur
        ;;
esac
