#!/bin/dash

# ☭

# this used to be a redshift script, hence the name, now it uses xsct. anyway
# input value for temp and gamma via dmenu
# if empty, use default value

ASKRED=$(printf "Redtime\nRemove" | dmenu -p "What to do?")
case "$ASKRED" in
    "Remove") xsct 0 && exit 0 ;;
    ""|"Redtime") ;;
    *) exit 1 ;;
esac

TEMP=$(printf "DEFAULT\nCancel" | dmenu -p "Temperature (default is 3000)")
case "$TEMP" in
    "Cancel") exit 0 ;;
    ""|"DEFAULT"|*[!0-9]*) TEMP=3000 ;;
    *) 
        if [ $TEMP -lt 700 -o $TEMP -gt 15000 ]; then
            printf "Invalid temperature or way too high, exiting...\n" ; exit 1
        else
            TEMP=$TEMP
        fi
    ;;
esac

BRIGHTNESS=$(printf "DEFAULT\nCancel" | dmenu -p "Brightness (0-1, default is 1)")
case "$BRIGHTNESS" in
    "Cancel") exit 0 ;;
    ""|"DEFAULT"|*[!0-9.]*|*.*.*) BRIGHTNESS=1 ;;
    *) 
        if [ $BRIGHTNESS -gt 1 ]; then
            BRIGHTNESS=0.$BRIGHTNESS
        elif [ $BRIGHTNESS -le 0 ]; then
            printf "Less than zero, exiting...\n" ; exit 1
        else
            BRIGHTNESS=$BRIGHTNESS
        fi
    ;;
esac

xsct $TEMP $BRIGHTNESS
