#!/bin/dash

# steam low resources mode

steam -no-browser +open steam://open/minigameslist

# steam removed -no-browser option, amazing
# fuck valve
# use steam-tui instead

#steam -dev -console -nofriendsui -no-dwrite -no-intro -nobigpicture -nofasthtml -nocrashmonitor -noshaders -no-shared-textures -disablehighdpi -cef-single-process -cef-in-process-gpu -single_core -cef-disable-d3d11 -cef-disable-sandbox -disable-winh264 -cef-force-32bit -no-cef-sandbox -vrdisable -cef-disable-breakpad

#steam -oldbigpicture -bigpicture -windowed 
