#!/bin/dash

if [ $# = 1 ]; then
  case $1 in
    "inc")
        wpctl set-volume @DEFAULT_SINK@ 2%+ ;;
    "dec")
        wpctl set-volume @DEFAULT_SINK@ 2%- ;;
    "sinc")
        wpctl set-volume @DEFAULT_SINK@ 5%+ ;;
    "sdec")
        wpctl set-volume @DEFAULT_SINK@ 5%- ;;
    "tog")
        wpctl set-mute @DEFAULT_SINK@ toggle ;;
    *)
      echo "Invalid option";;
  esac
fi

volume=$(pactl list sinks|awk '$1=="Volume:" {print $5}')
muted=$(pactl list sinks|awk '$1=="Mute:" {print $2}')

if [ "$muted" = "yes" ]; then
    notify-send -t 1500 -h string:x-canonical-private-synchronous:volume "Volume: muted"
else
    notify-send -t 1500 -h string:x-canonical-private-synchronous:volume "Volume: $volume" # this -h is working for now
fi
