#!/bin/sh

# maybe will reuse this bit of code if i can make what i want work

#case $1 in
#   *.png)
#       feh --bg-fill $1
#       ;;
#   *.jpg)
#       feh --bg-fill $1
#       ;;
#   *.jpeg)
#       feh --bg-fill $1
#       ;;
#esac

feh --bg-fill $1

mv $HOME/.fehbg $HOME/.scripts/fehbg
