#!/bin/bash

time=$(date +%H)

manha=("Bom dia," "Dia," "Opa," "Salve," "Good morning," "Mornin'," "Hi there," "Sup," "Bonjour," "Bon matin," "Salut," "Coucou," "おはよう、" "おはようございます、" "こんにちは、")

tarde=("Boa tarde," "Suave?" "Good afternoon," "Wassup," "Bonjour," "Salut," "Bonne après-midi," "こんにちは、")

noite=("Boa noite," "Como foi o dia?" "Good night," "All chill?" "Bonsoir," "Comment était ta journée ?" "Tranquille ?" "おやすみ、" "おやすみなさい、" "今日はどうだった？")

descanse=("Descanse bem e até amanhã, $USER" "Durma bem e bons sonhos, $USER" "Rest well, $USER" "Sleep tight, $USER" "Repose-toi et beaux rêves, $USER" "Repose-toi bien" "おやすみなさい！よく休んで、カラフルな夢を見てください、$USER" "おやすみ！素晴らしい休息をお過ごしください、$USER")

#choose random phrase
random_manha="${manha[$((RANDOM % ${#manha[@]}))]}"
random_tarde="${tarde[$((RANDOM % ${#tarde[@]}))]}"
random_noite="${noite[$((RANDOM % ${#noite[@]}))]}"
random_descanse="${descanse[$((RANDOM % ${#descanse[@]}))]}"

case $time in
    05|06|07|08|09|10|11)
        notify-send -h string:x-canonical-private-synchronous:welcome -t 15000 "$random_manha $USER"
        ;;
    12|13|14|15|16|17)
        notify-send -h string:x-canonical-private-synchronous:welcome -t 15000 "$random_tarde $USER"
        ;;
    18|19|20|21)
        notify-send -h string:x-canonical-private-synchronous:welcome -t 15000 "$random_noite $USER"
        ;;
    *)
        notify-send -h string:x-canonical-private-synchronous:welcome -t 15000 "$random_descanse"
        ;;
esac
